### PR TITLE
Reduce k8s metadata logs

### PR DESCRIPTION
**Pull request by pawelbojanowski**
We need more control over Kubernetes Metadata which is pushed to SumoLogic.
Setting `sumologic.com/kubernetes_meta_reduce: "true"` will reduce the Kubernetes metadata leaving only ```"kubernetes":{"container_name":"...","namespace_name":"...","pod_name":"...","host":"...",}``` which should be sufficient to identify the pod.

### CODE REVIEW

**Comment by frankreno** [comment]
@pawelbojanowski I like adding this feature.  However, I would like to keep the same behavior of having a global option or per pod option. I can imagine situations where you would want this to be globally set this way and have the option to disable or enable it via pod annotation.  So I think what we should do is add a property that can be configured globally to reduce this metadata (default to `false` to preserve backward compatibility and still have the annotation to have more fine-grained control. What do you think?

**Comment by pawelbojanowski** [comment]
@frankreno Agree, sounds reasonable. What do you think about having global env variable `KUBERNETES_META_REDUCE` (default `false`) that will allow to reduce metadata logs from all pods and per pod control via annotation `sumologic.com/kubernetesMetaReduce`?

**Comment by frankreno** [comment]
@pawelbojanowski pinging again.  Would like to merge this and cut a new release with the 2 other PRs that were merged....

**Comment by pawelbojanowski** [comment]
@frankreno Feature added, tests & readme updated.

**Comment by frankreno** [comment]
Thanks @pawelbojanowski - will get a new release with this and the other PRs out soon

**Comment by frankreno** [comment]
v2.1.0 is out with this change

**Pull request merged**
