### PR TITLE
Add S3 plugin & usage example

### LINKED ISSUE #63: Feature request: Allow the ability to data forward to S3 at the fluentD plugin level
I want the ability to "T" (data forward) my data to sumo logic and another source like s3 at the fluentD plugin level. The use case here is if I want to filter certain data that I send to Sumo Logic, but I want a back up of all my data I need this ability.

### PR DESCRIPTION
**Pull request by voxxit**
Fixes #63. Please let me know if there are any other examples y'all can think of? I wanted to be as generic as possible.

### CODE REVIEW

**Comment by frankreno** [comment]
LGTM, thanks for the add! Will get a new version of the image pushed to DockerHub that has the S3 plugin in...

**Comment by frankreno** [comment]
v1.18 and latest now have this change, thanks again!

**Comment by emptywee** [comment]
Isn't it going to consume events if it's configured like it was suggested? If <match kube-**> matches an event, the event would be considered consumed and there will be no copy to sumo, right? But the purpose is to back up to S3 as well. If I am reading the fluentd docs right, of course.

**Comment by frankreno** [comment]
@emptywee you are 100% correct, I knew this and completely skimmed over that fact.  So the good news is we can use `copy` to make it work, we just need to beef up the example a bit...

**Comment by frankreno** [comment]
@emptywee @voxxit - sorry for the delay. I have updated the README with the steps on how to use multiple outputs using the `copy` plugin because as @emptywee pointed out, this configuration would not make it to both places.

**Comment by voxxit** [comment]
@frankreno Gah, you're right. My bad! Thanks for helping out with the update. 👍

**Pull request merged**
