### PR TITLE
Add RBAC permissions

### PR DESCRIPTION
**Pull request by AlexB138**
Fixes: https://github.com/SumoLogic/fluentd-kubernetes-sumologic/issues/39

### CODE REVIEW

**Comment by AlexB138** [comment]
Does this need anything else, @stevezau @frankreno ?

**Comment by frankreno** [comment]
@AlexB138 : First off thank you for the PR.  This looks good.  However, I am wondering if we should have 2 YAML files.  One with RBAC, one without.  That would be more in sync with a lot of the YAML files provided by k8s in their docs.  Thoughts?

**Comment by AlexB138** [comment]
Yeah, I've seen a couple of projects do that as well. I think the way to do it is to have them in separate directories. I say this because doing `kubectl apply -f <directory>` is a common workflow for provisioning and having two yaml files in the same directory with different configs for the same resources would break that pattern.

I'll update the PR to have /daemonset/rbac/fluentd.yaml and daemonset/nonrbac/fluentd.yaml, if that works for you.

**Comment by frankreno** [comment]
That sounds great.

**Comment by AlexB138** [comment]
@frankreno Alright, broken out as discussed and updated the README!

**Comment by moos3** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 

I just had to figure this stuff out on my own. Please merge in!

**Pull request merged**
