### PR TITLE
Control adding time and stream

### PR DESCRIPTION
**Pull request by pawelbojanowski**
I think more control over `time` and `stream` would be a cool feature. In some cases, `stream` is always the same (e.g. `stdout`) and sometimes there is no need to have timestamp and time.

### CODE REVIEW

**Comment by frankreno** [comment]
I like the feature.  However, rather than rely on ENV, I would like to make it part of the configuration.  

https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/f2d42b33053380a5a1cbeeb825126d05303d936b/lib/fluent/plugin/filter_kubernetes_sumologic.rb#L21

So the environment variable gets passed to the configuration instead of just using the ENV in code.

**Comment by pawelbojanowski** [comment]
@frankreno Moved the checks to conf

**Comment by pawelbojanowski** [comment]
Hey @frankreno I've added test for `ADD_TIME` variable. I also checked README and SystemD and I believe everything is up-to-date.

**Comment by frankreno** [comment]
v2.1.0 is out with this change

**Pull request merged**
